# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-14 15:48
from __future__ import unicode_literals

import DjangoUeditor.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, verbose_name='文章标题')),
                ('content', DjangoUeditor.models.UEditorField()),
                ('publishTime', models.DateTimeField(auto_now_add=True)),
                ('modifyTime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-publishTime'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='用户名称')),
                ('password', models.CharField(max_length=50, verbose_name='用户密码')),
                ('age', models.IntegerField(default=18, verbose_name='用户年龄')),
                ('nickname', models.CharField(max_length=100, verbose_name='用户昵称')),
                ('tel', models.IntegerField(default=0, verbose_name='手机号码')),
                ('birthday', models.DateTimeField(default=datetime.datetime(2018, 10, 14, 23, 48, 28, 327046), verbose_name='用户生日')),
                ('header', models.ImageField(default='static/img/1.png', upload_to='static/img/headers/', verbose_name='用户头像')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.User'),
        ),
    ]
